name: Build and Deploy to AWS

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'  # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Generate build
        run: npm run build

      - name: List build directory for debugging
        run: ls -al build

      # Share artifact inside workflow
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build/

      - name: List current directory for debugging
        run: ls -al

      - name: List build directory for debugging
        run: ls -al build/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: aws s3 sync build/ s3://activity3reactproject/ --delete
